grafana:
  adminPassword: pharos-admin
  service:
    type: ClusterIP

prometheus:
  prometheusSpec:
    retention: 6h
    resources:
      requests:
        cpu: 200m
        memory: 512Mi
      limits:
        memory: 1Gi

alertmanager:
  alertmanagerSpec:
    resources:
      requests:
        cpu: 50m
        memory: 128Mi

prometheusOperator:
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
